[workspace]
resolver = "3"
members = ["server", "msstore"]

[workspace.dependencies]
anyhow = "1"

tokio = { version = "1", features = ["full"] }

axum = "0.8"

serde = "1"
serde_json = "1"

rust-embed = "8.7"
